# Generated by Django 5.2.5 on 2026-08-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_gemini_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thinking',
            field=models.TextField(blank=True, default='', help_text='Model native reasoning text (e.g. DeepSeek reasoning_content) captured during streaming.'),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list, help_text='List of {tool, arguments} dicts executed while producing this reply.'),
        ),
    ]
