# Generated by Django 5.2.5 on 2026-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_message_thinking_message_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='origin',
            field=models.CharField(choices=[('topic', 'Topic workspace'), ('chat', 'Discord-style chat page')], default='topic', help_text='Which interface created this session; the two interfaces keep independent session pools.', max_length=10),
        ),
    ]
