# Generated by Django 5.2.5 on 2026-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_chatsession_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized LLM usage for this reply: {prompt_tokens, completion_tokens, total_tokens, cached_tokens}.'),
        ),
    ]
