# Generated by Django 5.2.5 on 2026-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_message_token_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfiguration',
            name='context_window',
            field=models.PositiveBigIntegerField(blank=True, help_text='Model context window in tokens; powers the accurate context-usage indicator.', null=True),
        ),
    ]
