# Generated by Django 5.2.5 on 2026-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_modelconfiguration_context_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_title_manual',
            field=models.BooleanField(default=False, help_text='When true, the auto title generator must not overwrite this title.'),
        ),
    ]
